from enum import StrEnum


class CONFIG(StrEnum):
    AUTO_DST = "auto_dst"
    CALCIUM_HARDNESS = "calcium_hardness"
    COOL_SETPOINT = "cool_setpoint"
    CYA = "cya"
    HEAT_MODE = "heat_mode"
    HEAT_SETPOINT = "heat_setpoint"
    HEAT_STATE = "heat_state"
    INTERFACE_TAB_FLAGS = "interface_tab_flags"
    IS_CELSIUS = "is_celsius"
    ORP_SETPOINT = "orp_setpoint"
    PH_SETPOINT = "ph_setpoint"
    POOL_SETPOINT = "pool_setpoint"
    SALT_TDS_PPM = "salt_tds_ppm"
    SATURATION = "saturation"
    SPA_SETPOINT = "spa_setpoint"
    SUPER_CHLOR_TIMER = "super_chlor_timer"
    SUPER_CHLORINATE = "super_chlorinate"


class SENSOR(StrEnum):
    ACTIVE_ALERT = "active_alert"
    AIR_TEMPERATURE = "air_temperature"
    CALCIUM_HARDNESS = "calcium_hardness"
    CLEANER_DELAY = "cleaner_delay"
    CORROSIVE = "corrosive"
    CYA = "cya"
    FLOW_ALARM = "flow_alarm"
    FREEZE_MODE = "freeze_mode"
    GPM_NOW = "gpm_now"
    ORP = "orp"
    ORP_DOSING_STATE = "orp_dosing_state"
    ORP_HIGH_ALARM = "orp_high_alarm"
    ORP_LAST_DOSE_TIME = "orp_last_dose_time"
    ORP_LAST_DOSE_VOLUME = "orp_last_dose_volume"
    ORP_LIMIT = "orp_limit"
    ORP_LOW_ALARM = "orp_low_alarm"
    ORP_NOW = "orp_now"
    ORP_SUPPLY_ALARM = "orp_supply_alarm"
    ORP_SUPPLY_LEVEL = "orp_supply_level"
    PH = "ph"
    PH_DOSING_STATE = "ph_dosing_state"
    PH_HIGH_ALARM = "ph_high_alarm"
    PH_LAST_DOSE_TIME = "ph_last_dose_time"
    PH_LAST_DOSE_VOLUME = "ph_last_dose_volume"
    PH_LIMIT = "ph_limit"
    PH_LOCKOUT = "ph_lockout"
    PH_LOW_ALARM = "ph_low_alarm"
    PH_NOW = "ph_now"
    PH_PROBE_WATER_TEMP = "ph_probe_water_temp"
    PH_SUPPLY_ALARM = "ph_supply_alarm"
    PH_SUPPLY_LEVEL = "ph_supply_level"
    POOL_DELAY = "pool_delay"
    PROBE_FAULT_ALARM = "probe_fault_alarm"
    RPM_NOW = "rpm_now"
    SALT_PPM = "salt_ppm"
    SALT_TDS_PPM = "salt_tds_ppm"
    SATURATION = "saturation"
    SCALING = "scaling"
    SPA_DELAY = "spa_delay"
    STATE = "state"
    TIMESTAMP = "timestamp"
    TIMESTAMP_HOST = "timestamp_host"
    TOTAL_ALKALINITY = "total_alkalinity"
    WATTS_NOW = "watts_now"
