EXPECTED_VERSION_DATA = {
    "adapter": {
        "firmware": {
            "name": "Protocol Adapter Firmware",
            "value": "POOL: 5.2 Build 736.0 Rel",
        }
    }
}

EXPECTED_CONFIG_DATA = {
    "controller": {
        "controller_id": 100,
        "configuration": {
            "body_type": {
                0: {"min_setpoint": 40, "max_setpoint": 104},
                1: {"min_setpoint": 40, "max_setpoint": 104},
            },
            "is_celsius": {"name": "Is Celsius", "value": 0},
            "controller_type": 13,
            "hardware_type": 0,
            "controller_data": 0,
            "generic_circuit_name": "Water Features",
            "circuit_count": 18,
            "color_count": 8,
            "color": [
                {"name": "White", "value": (255, 255, 255)},
                {"name": "Light Green", "value": (160, 255, 160)},
                {"name": "Green", "value": (0, 255, 80)},
                {"name": "Cyan", "value": (0, 255, 200)},
                {"name": "Blue", "value": (100, 140, 255)},
                {"name": "Lavender", "value": (230, 130, 255)},
                {"name": "Magenta", "value": (255, 0, 128)},
                {"name": "Light Magenta", "value": (255, 180, 210)},
            ],
            "interface_tab_flags": 127,
            "show_alarms": 0,
        },
        "model": {"name": "Model", "value": "EasyTouch2 8"},
        "equipment": {
            "flags": 98360,
            "list": [
                "INTELLIBRITE",
                "INTELLIFLO_0",
                "INTELLIFLO_1",
                "INTELLICHEM",
                "HYBRID_HEATER",
            ],
        },
    },
    "circuit": {
        500: {
            "circuit_id": 500,
            "name": "Spa",
            "configuration": {
                "name_index": 71,
                "flags": 1,
                "default_runtime": 720,
                "unknown_at_offset_62": 0,
                "unknown_at_offset_63": 0,
            },
            "function": 1,
            "interface": 1,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 1,
        },
        501: {
            "circuit_id": 501,
            "name": "Waterfall",
            "configuration": {
                "name_index": 85,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_94": 0,
                "unknown_at_offset_95": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 2,
        },
        502: {
            "circuit_id": 502,
            "name": "Pool Light",
            "configuration": {
                "name_index": 62,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_126": 0,
                "unknown_at_offset_127": 0,
            },
            "function": 16,
            "interface": 3,
            "color": {"color_set": 2, "color_position": 0, "color_stagger": 10},
            "device_id": 3,
        },
        503: {
            "circuit_id": 503,
            "name": "Spa Light",
            "configuration": {
                "name_index": 73,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_158": 0,
                "unknown_at_offset_159": 0,
            },
            "function": 16,
            "interface": 3,
            "color": {"color_set": 7, "color_position": 0, "color_stagger": 10},
            "device_id": 4,
        },
        504: {
            "circuit_id": 504,
            "name": "Cleaner",
            "configuration": {
                "name_index": 21,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_186": 0,
                "unknown_at_offset_187": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 5,
        },
        505: {
            "circuit_id": 505,
            "name": "Pool Low",
            "configuration": {
                "name_index": 63,
                "flags": 1,
                "default_runtime": 720,
                "unknown_at_offset_214": 0,
                "unknown_at_offset_215": 0,
            },
            "function": 2,
            "interface": 0,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 6,
        },
        506: {
            "circuit_id": 506,
            "name": "Yard Light",
            "configuration": {
                "name_index": 91,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_246": 0,
                "unknown_at_offset_247": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 7,
        },
        507: {
            "circuit_id": 507,
            "name": "Aux 6",
            "configuration": {
                "name_index": 7,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_274": 0,
                "unknown_at_offset_275": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 8,
        },
        508: {
            "circuit_id": 508,
            "name": "Pool High",
            "configuration": {
                "name_index": 61,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_306": 0,
                "unknown_at_offset_307": 0,
            },
            "function": 5,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 9,
        },
        510: {
            "circuit_id": 510,
            "name": "Feature 1",
            "configuration": {
                "name_index": 93,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_338": 0,
                "unknown_at_offset_339": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 11,
        },
        511: {
            "circuit_id": 511,
            "name": "Feature 2",
            "configuration": {
                "name_index": 94,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_370": 0,
                "unknown_at_offset_371": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 12,
        },
        512: {
            "circuit_id": 512,
            "name": "Feature 3",
            "configuration": {
                "name_index": 95,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_402": 0,
                "unknown_at_offset_403": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 13,
        },
        513: {
            "circuit_id": 513,
            "name": "Feature 4",
            "configuration": {
                "name_index": 96,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_434": 0,
                "unknown_at_offset_435": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 14,
        },
        514: {
            "circuit_id": 514,
            "name": "Feature 5",
            "configuration": {
                "name_index": 97,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_466": 0,
                "unknown_at_offset_467": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 15,
        },
        515: {
            "circuit_id": 515,
            "name": "Feature 6",
            "configuration": {
                "name_index": 98,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_498": 0,
                "unknown_at_offset_499": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 16,
        },
        516: {
            "circuit_id": 516,
            "name": "Feature 7",
            "configuration": {
                "name_index": 99,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_530": 0,
                "unknown_at_offset_531": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 17,
        },
        517: {
            "circuit_id": 517,
            "name": "Feature 8",
            "configuration": {
                "name_index": 100,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_562": 0,
                "unknown_at_offset_563": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 18,
        },
        519: {
            "circuit_id": 519,
            "name": "AuxEx",
            "configuration": {
                "name_index": 92,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_590": 0,
                "unknown_at_offset_591": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 20,
        },
    },
    "pump": {
        0: {"data": 70},
        1: {"data": 0},
        2: {"data": 0},
        3: {"data": 0},
        4: {"data": 0},
        5: {"data": 0},
        6: {"data": 0},
        7: {"data": 0},
    },
}

EXPECTED_STATUS_DATA = {
    "controller": {
        "status": 1,
        "sensor": {
            "freeze_mode": {"name": "Freeze Mode", "value": 0},
            "pool_delay": {"name": "Pool Delay", "value": 0},
            "spa_delay": {"name": "Spa Delay", "value": 0},
            "cleaner_delay": {"name": "Cleaner Delay", "value": 0},
            "air_temperature": {
                "name": "Air Temperature",
                "value": 57,
                "unit": "°F",
                "device_type": "temperature",
                "state_type": "measurement",
            },
            "ph": {
                "name": "pH",
                "value": 7.48,
                "unit": "pH",
                "state_type": "measurement",
            },
            "orp": {
                "name": "ORP",
                "value": 701,
                "unit": "mV",
                "state_type": "measurement",
            },
            "saturation": {
                "name": "Saturation Index",
                "value": -0.13,
                "unit": "lsi",
                "state_type": "measurement",
            },
            "salt_ppm": {
                "name": "Salt",
                "value": 0,
                "unit": "ppm",
                "state_type": "measurement",
            },
            "ph_supply_level": {
                "name": "pH Supply Level",
                "value": 3,
                "state_type": "measurement",
            },
            "orp_supply_level": {
                "name": "ORP Supply Level",
                "value": 4,
                "state_type": "measurement",
            },
            "active_alarm": {
                "name": "Active Alarm",
                "value": 1,
                "device_type": "alarm",
            },
        },
        "configuration": {
            "remotes": 0,
            "unknown_at_offset_09": 0,
            "unknown_at_offset_10": 0,
            "unknown_at_offset_11": 0,
        },
    },
    "body": {
        0: {
            "body_type": 0,
            "name": "Pool",
            "last_temperature": {
                "name": "Last Pool Temperature",
                "value": 56,
                "unit": "°F",
                "device_type": "temperature",
                "state_type": "measurement",
            },
            "heat_state": {
                "name": "Pool Heat",
                "value": 0,
                "device_type": "enum",
                "enum_options": ["Off", "Solar", "Heater", "Both"],
            },
            "heat_setpoint": {
                "name": "Pool Heat Set Point",
                "value": 86,
                "unit": "°F",
                "device_type": "temperature",
            },
            "cool_setpoint": {
                "name": "Pool Cool Set Point",
                "value": 100,
                "unit": "°F",
                "device_type": "temperature",
            },
            "heat_mode": {
                "name": "Pool Heat Mode",
                "value": 0,
                "device_type": "enum",
                "enum_options": [
                    "Off",
                    "Solar",
                    "Solar Preferred",
                    "Heater",
                    "Don't Change",
                ],
            },
        },
        1: {
            "body_type": 1,
            "name": "Spa",
            "last_temperature": {
                "name": "Last Spa Temperature",
                "value": 97,
                "unit": "°F",
                "device_type": "temperature",
                "state_type": "measurement",
            },
            "heat_state": {
                "name": "Spa Heat",
                "value": 0,
                "device_type": "enum",
                "enum_options": ["Off", "Solar", "Heater", "Both"],
            },
            "heat_setpoint": {
                "name": "Spa Heat Set Point",
                "value": 97,
                "unit": "°F",
                "device_type": "temperature",
            },
            "cool_setpoint": {
                "name": "Spa Cool Set Point",
                "value": 57,
                "unit": "°F",
                "device_type": "temperature",
            },
            "heat_mode": {
                "name": "Spa Heat Mode",
                "value": 3,
                "device_type": "enum",
                "enum_options": [
                    "Off",
                    "Solar",
                    "Solar Preferred",
                    "Heater",
                    "Don't Change",
                ],
            },
        },
    },
    "circuit": {
        500: {
            "circuit_id": 500,
            "value": 0,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "configuration": {"delay": 0},
        },
        501: {
            "circuit_id": 501,
            "value": 0,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "configuration": {"delay": 0},
        },
        502: {
            "circuit_id": 502,
            "value": 1,
            "color": {"color_set": 2, "color_position": 0, "color_stagger": 10},
            "configuration": {"delay": 0},
        },
        503: {
            "circuit_id": 503,
            "value": 1,
            "color": {"color_set": 7, "color_position": 0, "color_stagger": 10},
            "configuration": {"delay": 0},
        },
        504: {
            "circuit_id": 504,
            "value": 1,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "configuration": {"delay": 0},
        },
        505: {
            "circuit_id": 505,
            "value": 0,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "configuration": {"delay": 0},
        },
        506: {
            "circuit_id": 506,
            "value": 1,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "configuration": {"delay": 0},
        },
        507: {
            "circuit_id": 507,
            "value": 0,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "configuration": {"delay": 0},
        },
        508: {
            "circuit_id": 508,
            "value": 0,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "configuration": {"delay": 0},
        },
        510: {
            "circuit_id": 510,
            "value": 0,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "configuration": {"delay": 0},
        },
        511: {
            "circuit_id": 511,
            "value": 0,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "configuration": {"delay": 0},
        },
        512: {
            "circuit_id": 512,
            "value": 0,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "configuration": {"delay": 0},
        },
        513: {
            "circuit_id": 513,
            "value": 0,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "configuration": {"delay": 0},
        },
        514: {
            "circuit_id": 514,
            "value": 0,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "configuration": {"delay": 0},
        },
        515: {
            "circuit_id": 515,
            "value": 0,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "configuration": {"delay": 0},
        },
        516: {
            "circuit_id": 516,
            "value": 0,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "configuration": {"delay": 0},
        },
        517: {
            "circuit_id": 517,
            "value": 0,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "configuration": {"delay": 0},
        },
        519: {
            "circuit_id": 519,
            "value": 0,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "configuration": {"delay": 0},
        },
    },
}

EXPECTED_PUMP_DATA = {
    "pump": {
        0: {
            "pump_type": 3,
            "state": {"name": "Default Pump", "value": 0},
            "watts_now": {
                "name": "Default Pump Watts Now",
                "value": 0,
                "unit": "W",
                "device_type": "power",
                "state_type": "measurement",
            },
            "rpm_now": {
                "name": "Default Pump RPM Now",
                "value": 0,
                "unit": "rpm",
                "state_type": "measurement",
            },
            "unknown_at_offset_16": 0,
            "gpm_now": {
                "name": "Default Pump GPM Now",
                "value": 0,
                "unit": "gpm",
                "state_type": "measurement",
            },
            "unknown_at_offset_24": 255,
            "preset": {
                0: {"device_id": 6, "setpoint": 2500, "is_rpm": 1},
                1: {"device_id": 9, "setpoint": 2800, "is_rpm": 1},
                2: {"device_id": 1, "setpoint": 3450, "is_rpm": 1},
                3: {"device_id": 0, "setpoint": 30, "is_rpm": 0},
                4: {"device_id": 0, "setpoint": 30, "is_rpm": 0},
                5: {"device_id": 0, "setpoint": 30, "is_rpm": 0},
                6: {"device_id": 0, "setpoint": 30, "is_rpm": 0},
                7: {"device_id": 0, "setpoint": 30, "is_rpm": 0},
            },
        }
    }
}

EXPECTED_CHEMISTRY_DATA = {
    "intellichem": {
        "unknown_at_offset_00": 42,
        "unknown_at_offset_04": 0,
        "sensor": {
            "ph_now": {
                "name": "pH Now",
                "value": 0.0,
                "unit": "pH",
                "state_type": "measurement",
            },
            "orp_now": {
                "name": "ORP Now",
                "value": 0,
                "unit": "mV",
                "state_type": "measurement",
            },
            "ph_supply_level": {
                "name": "pH Supply Level",
                "value": 3,
                "state_type": "measurement",
            },
            "orp_supply_level": {
                "name": "ORP Supply Level",
                "value": 4,
                "state_type": "measurement",
            },
            "saturation": {
                "name": "Saturation Index",
                "value": -0.13,
                "unit": "lsi",
                "state_type": "measurement",
            },
            "ph_probe_water_temp": {
                "name": "pH Probe Water Temperature",
                "value": 56,
                "unit": "°F",
                "device_type": "temperature",
                "state_type": "measurement",
            },
        },
        "configuration": {
            "ph_setpoint": {"name": "pH Setpoint", "value": 7.5, "unit": "pH"},
            "orp_setpoint": {"name": "ORP Setpoint", "value": 700, "unit": "mV"},
            "calcium_harness": {
                "name": "Calcium Hardness",
                "value": 740,
                "unit": "ppm",
            },
            "cya": {"name": "Cyanuric Acid", "value": 36, "unit": "ppm"},
            "total_alkalinity": {
                "name": "Total Alkalinity",
                "value": 70,
                "unit": "ppm",
            },
            "salt_tds_ppm": {"name": "Salt/TDS", "value": 1000, "unit": "ppm"},
            "probe_is_celsius": 0,
            "flags": 32,
        },
        "dose_status": {
            "ph_last_dose_time": {
                "name": "Last pH Dose Time",
                "value": 5,
                "unit": "sec",
                "device_type": "duration",
                "state_type": "total_increasing",
            },
            "orp_last_dose_time": {
                "name": "Last ORP Dose Time",
                "value": 2,
                "unit": "sec",
                "device_type": "duration",
                "state_type": "total_increasing",
            },
            "ph_last_dose_volume": {
                "name": "Last pH Dose Volume",
                "value": 10,
                "unit": "mL",
                "device_type": "volume",
                "state_type": "total_increasing",
            },
            "orp_last_dose_volume": {
                "name": "Last ORP Dose Volume",
                "value": 4,
                "unit": "mL",
                "device_type": "volume",
                "state_type": "total_increasing",
            },
            "flags": 165,
            "ph_dosing_state": {
                "name": "pH Dosing State",
                "value": 2,
                "device_type": "enum",
                "enum_options": ["Dosing", "Mixing", "Monitoring"],
            },
            "orp_dosing_state": {
                "name": "ORP Dosing State",
                "value": 2,
                "device_type": "enum",
                "enum_options": ["Dosing", "Mixing", "Monitoring"],
            },
        },
        "alarm": {
            "flags": 129,
            "flow_alarm": {"name": "Flow Alarm", "value": 1, "device_type": "alarm"},
            "ph_high_alarm": {
                "name": "pH HIGH Alarm",
                "value": 0,
                "device_type": "alarm",
            },
            "ph_low_alarm": {
                "name": "pH LOW Alarm",
                "value": 0,
                "device_type": "alarm",
            },
            "orp_high_alarm": {
                "name": "ORP HIGH Alarm",
                "value": 0,
                "device_type": "alarm",
            },
            "orp_low_alarm": {
                "name": "ORP LOW Alarm",
                "value": 0,
                "device_type": "alarm",
            },
            "ph_supply_alarm": {
                "name": "pH Supply Alarm",
                "value": 0,
                "device_type": "alarm",
            },
            "orp_supply_alarm": {
                "name": "ORP Supply Alarm",
                "value": 0,
                "device_type": "alarm",
            },
            "probe_fault_alarm": {
                "name": "Probe Fault",
                "value": 1,
                "device_type": "alarm",
            },
        },
        "alert": {
            "flags": 0,
            "ph_lockout": {"name": "pH Lockout", "value": 0},
            "ph_limit": {"name": "pH Dose Limit Reached", "value": 0},
            "orp_limit": {"name": "ORP Dose Limit Reached", "value": 0},
        },
        "firmware": {"name": "IntelliChem Firmware", "value": "1.060"},
        "water_balance": {
            "flags": 0,
            "corrosive": {"name": "SI Corrosive", "value": 0, "device_type": "alarm"},
            "scaling": {"name": "SI Scaling", "value": 0, "device_type": "alarm"},
        },
        "unknown_at_offset_44": 0,
        "unknown_at_offset_45": 0,
        "unknown_at_offset_46": 0,
    }
}

EXPECTED_SCG_DATA = {
    "scg": {
        "scg_present": 0,
        "sensor": {
            "state": {"name": "SCG State", "value": 1},
            "salt_ppm": {
                "name": "SCG Salt",
                "value": 0,
                "unit": "ppm",
                "state_type": "measurement",
            },
        },
        "configuration": {
            "pool_setpoint": {"name": "Pool SCG Setpoint", "value": 50, "unit": "%"},
            "spa_setpoint": {"name": "Spa SCG Setpoint", "value": 0, "unit": "%"},
            "super_chlor_timer": {
                "name": "SCG Super Chlorination Timer",
                "value": 0,
                "unit": "hr",
            },
        },
        "flags": 0,
    }
}

EXPECTED_COLOR_DATA = {
    "controller": {
        "color_lights": {"color_mode": 12, "progress": 14, "limit": 15, "text": ""}
    }
}

EXPECTED_COMPLETE_DATA = {
    "adapter": {
        "firmware": {"name": "Protocol Adapter Firmware", "value": "fake 0.0.3"}
    },
    "controller": {
        "controller_id": 100,
        "configuration": {
            "body_type": {
                0: {"min_setpoint": 40, "max_setpoint": 104},
                1: {"min_setpoint": 40, "max_setpoint": 104},
            },
            "is_celsius": {"name": "Is Celsius", "value": 0},
            "controller_type": 13,
            "hardware_type": 0,
            "controller_data": 0,
            "generic_circuit_name": "Water Features",
            "circuit_count": 18,
            "color_count": 8,
            "color": [
                {"name": "White", "value": (255, 255, 255)},
                {"name": "Light Green", "value": (160, 255, 160)},
                {"name": "Green", "value": (0, 255, 80)},
                {"name": "Cyan", "value": (0, 255, 200)},
                {"name": "Blue", "value": (100, 140, 255)},
                {"name": "Lavender", "value": (230, 130, 255)},
                {"name": "Magenta", "value": (255, 0, 128)},
                {"name": "Light Magenta", "value": (255, 180, 210)},
            ],
            "interface_tab_flags": 127,
            "show_alarms": 0,
            "remotes": 0,
            "unknown_at_offset_09": 0,
            "unknown_at_offset_10": 0,
            "unknown_at_offset_11": 0,
        },
        "model": {"name": "Model", "value": "EasyTouch2 8"},
        "equipment": {
            "flags": 98360,
            "list": [
                "INTELLIBRITE",
                "INTELLIFLO_0",
                "INTELLIFLO_1",
                "INTELLICHEM",
                "HYBRID_HEATER",
            ],
        },
        "status": 1,
        "sensor": {
            "freeze_mode": {"name": "Freeze Mode", "value": 0},
            "pool_delay": {"name": "Pool Delay", "value": 0},
            "spa_delay": {"name": "Spa Delay", "value": 0},
            "cleaner_delay": {"name": "Cleaner Delay", "value": 0},
            "air_temperature": {
                "name": "Air Temperature",
                "value": 57,
                "unit": "°F",
                "device_type": "temperature",
                "state_type": "measurement",
            },
            "ph": {
                "name": "pH",
                "value": 7.48,
                "unit": "pH",
                "state_type": "measurement",
            },
            "orp": {
                "name": "ORP",
                "value": 701,
                "unit": "mV",
                "state_type": "measurement",
            },
            "saturation": {
                "name": "Saturation Index",
                "value": -0.13,
                "unit": "lsi",
                "state_type": "measurement",
            },
            "salt_ppm": {
                "name": "Salt",
                "value": 0,
                "unit": "ppm",
                "state_type": "measurement",
            },
            "ph_supply_level": {
                "name": "pH Supply Level",
                "value": 3,
                "state_type": "measurement",
            },
            "orp_supply_level": {
                "name": "ORP Supply Level",
                "value": 4,
                "state_type": "measurement",
            },
            "active_alarm": {
                "name": "Active Alarm",
                "value": 1,
                "device_type": "alarm",
            },
        },
    },
    "circuit": {
        500: {
            "circuit_id": 500,
            "name": "Spa",
            "configuration": {
                "name_index": 71,
                "flags": 1,
                "default_runtime": 720,
                "unknown_at_offset_62": 0,
                "unknown_at_offset_63": 0,
                "delay": 0,
            },
            "function": 1,
            "interface": 1,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 1,
            "value": 0,
        },
        501: {
            "circuit_id": 501,
            "name": "Waterfall",
            "configuration": {
                "name_index": 85,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_94": 0,
                "unknown_at_offset_95": 0,
                "delay": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 2,
            "value": 0,
        },
        502: {
            "circuit_id": 502,
            "name": "Pool Light",
            "configuration": {
                "name_index": 62,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_126": 0,
                "unknown_at_offset_127": 0,
                "delay": 0,
            },
            "function": 16,
            "interface": 3,
            "color": {"color_set": 2, "color_position": 0, "color_stagger": 10},
            "device_id": 3,
            "value": 1,
        },
        503: {
            "circuit_id": 503,
            "name": "Spa Light",
            "configuration": {
                "name_index": 73,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_158": 0,
                "unknown_at_offset_159": 0,
                "delay": 0,
            },
            "function": 16,
            "interface": 3,
            "color": {"color_set": 7, "color_position": 0, "color_stagger": 10},
            "device_id": 4,
            "value": 1,
        },
        504: {
            "circuit_id": 504,
            "name": "Cleaner",
            "configuration": {
                "name_index": 21,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_186": 0,
                "unknown_at_offset_187": 0,
                "delay": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 5,
            "value": 1,
        },
        505: {
            "circuit_id": 505,
            "name": "Pool Low",
            "configuration": {
                "name_index": 63,
                "flags": 1,
                "default_runtime": 720,
                "unknown_at_offset_214": 0,
                "unknown_at_offset_215": 0,
                "delay": 0,
            },
            "function": 2,
            "interface": 0,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 6,
            "value": 0,
        },
        506: {
            "circuit_id": 506,
            "name": "Yard Light",
            "configuration": {
                "name_index": 91,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_246": 0,
                "unknown_at_offset_247": 0,
                "delay": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 7,
            "value": 1,
        },
        507: {
            "circuit_id": 507,
            "name": "Aux 6",
            "configuration": {
                "name_index": 7,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_274": 0,
                "unknown_at_offset_275": 0,
                "delay": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 8,
            "value": 0,
        },
        508: {
            "circuit_id": 508,
            "name": "Pool High",
            "configuration": {
                "name_index": 61,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_306": 0,
                "unknown_at_offset_307": 0,
                "delay": 0,
            },
            "function": 5,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 9,
            "value": 0,
        },
        510: {
            "circuit_id": 510,
            "name": "Feature 1",
            "configuration": {
                "name_index": 93,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_338": 0,
                "unknown_at_offset_339": 0,
                "delay": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 11,
            "value": 0,
        },
        511: {
            "circuit_id": 511,
            "name": "Feature 2",
            "configuration": {
                "name_index": 94,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_370": 0,
                "unknown_at_offset_371": 0,
                "delay": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 12,
            "value": 0,
        },
        512: {
            "circuit_id": 512,
            "name": "Feature 3",
            "configuration": {
                "name_index": 95,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_402": 0,
                "unknown_at_offset_403": 0,
                "delay": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 13,
            "value": 0,
        },
        513: {
            "circuit_id": 513,
            "name": "Feature 4",
            "configuration": {
                "name_index": 96,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_434": 0,
                "unknown_at_offset_435": 0,
                "delay": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 14,
            "value": 0,
        },
        514: {
            "circuit_id": 514,
            "name": "Feature 5",
            "configuration": {
                "name_index": 97,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_466": 0,
                "unknown_at_offset_467": 0,
                "delay": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 15,
            "value": 0,
        },
        515: {
            "circuit_id": 515,
            "name": "Feature 6",
            "configuration": {
                "name_index": 98,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_498": 0,
                "unknown_at_offset_499": 0,
                "delay": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 16,
            "value": 0,
        },
        516: {
            "circuit_id": 516,
            "name": "Feature 7",
            "configuration": {
                "name_index": 99,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_530": 0,
                "unknown_at_offset_531": 0,
                "delay": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 17,
            "value": 0,
        },
        517: {
            "circuit_id": 517,
            "name": "Feature 8",
            "configuration": {
                "name_index": 100,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_562": 0,
                "unknown_at_offset_563": 0,
                "delay": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 18,
            "value": 0,
        },
        519: {
            "circuit_id": 519,
            "name": "AuxEx",
            "configuration": {
                "name_index": 92,
                "flags": 0,
                "default_runtime": 720,
                "unknown_at_offset_590": 0,
                "unknown_at_offset_591": 0,
                "delay": 0,
            },
            "function": 0,
            "interface": 2,
            "color": {"color_set": 0, "color_position": 0, "color_stagger": 0},
            "device_id": 20,
            "value": 0,
        },
    },
    "pump": {
        0: {
            "data": 70,
            "pump_type": 3,
            "state": {"name": "Pool Low Pump", "value": 0},
            "watts_now": {
                "name": "Pool Low Pump Watts Now",
                "value": 0,
                "unit": "W",
                "device_type": "power",
                "state_type": "measurement",
            },
            "rpm_now": {
                "name": "Pool Low Pump RPM Now",
                "value": 0,
                "unit": "rpm",
                "state_type": "measurement",
            },
            "unknown_at_offset_16": 0,
            "gpm_now": {
                "name": "Pool Low Pump GPM Now",
                "value": 0,
                "unit": "gpm",
                "state_type": "measurement",
            },
            "unknown_at_offset_24": 255,
            "preset": {
                0: {"device_id": 6, "setpoint": 2500, "is_rpm": 1},
                1: {"device_id": 9, "setpoint": 2800, "is_rpm": 1},
                2: {"device_id": 1, "setpoint": 3450, "is_rpm": 1},
                3: {"device_id": 0, "setpoint": 30, "is_rpm": 0},
                4: {"device_id": 0, "setpoint": 30, "is_rpm": 0},
                5: {"device_id": 0, "setpoint": 30, "is_rpm": 0},
                6: {"device_id": 0, "setpoint": 30, "is_rpm": 0},
                7: {"device_id": 0, "setpoint": 30, "is_rpm": 0},
            },
        },
        1: {"data": 0},
        2: {"data": 0},
        3: {"data": 0},
        4: {"data": 0},
        5: {"data": 0},
        6: {"data": 0},
        7: {"data": 0},
    },
    "body": {
        0: {
            "body_type": 0,
            "min_setpoint": 40,
            "max_setpoint": 104,
            "name": "Pool",
            "last_temperature": {
                "name": "Last Pool Temperature",
                "value": 56,
                "unit": "°F",
                "device_type": "temperature",
                "state_type": "measurement",
            },
            "heat_state": {
                "name": "Pool Heat",
                "value": 0,
                "device_type": "enum",
                "enum_options": ["Off", "Solar", "Heater", "Both"],
            },
            "heat_setpoint": {
                "name": "Pool Heat Set Point",
                "value": 86,
                "unit": "°F",
                "device_type": "temperature",
            },
            "cool_setpoint": {
                "name": "Pool Cool Set Point",
                "value": 100,
                "unit": "°F",
                "device_type": "temperature",
            },
            "heat_mode": {
                "name": "Pool Heat Mode",
                "value": 0,
                "device_type": "enum",
                "enum_options": [
                    "Off",
                    "Solar",
                    "Solar Preferred",
                    "Heater",
                    "Don't Change",
                ],
            },
        },
        1: {
            "body_type": 1,
            "min_setpoint": 40,
            "max_setpoint": 104,
            "name": "Spa",
            "last_temperature": {
                "name": "Last Spa Temperature",
                "value": 97,
                "unit": "°F",
                "device_type": "temperature",
                "state_type": "measurement",
            },
            "heat_state": {
                "name": "Spa Heat",
                "value": 0,
                "device_type": "enum",
                "enum_options": ["Off", "Solar", "Heater", "Both"],
            },
            "heat_setpoint": {
                "name": "Spa Heat Set Point",
                "value": 97,
                "unit": "°F",
                "device_type": "temperature",
            },
            "cool_setpoint": {
                "name": "Spa Cool Set Point",
                "value": 57,
                "unit": "°F",
                "device_type": "temperature",
            },
            "heat_mode": {
                "name": "Spa Heat Mode",
                "value": 3,
                "device_type": "enum",
                "enum_options": [
                    "Off",
                    "Solar",
                    "Solar Preferred",
                    "Heater",
                    "Don't Change",
                ],
            },
        },
    },
    "intellichem": {
        "unknown_at_offset_00": 42,
        "unknown_at_offset_04": 0,
        "sensor": {
            "ph_now": {
                "name": "pH Now",
                "value": 0.0,
                "unit": "pH",
                "state_type": "measurement",
            },
            "orp_now": {
                "name": "ORP Now",
                "value": 0,
                "unit": "mV",
                "state_type": "measurement",
            },
            "ph_supply_level": {
                "name": "pH Supply Level",
                "value": 3,
                "state_type": "measurement",
            },
            "orp_supply_level": {
                "name": "ORP Supply Level",
                "value": 4,
                "state_type": "measurement",
            },
            "saturation": {
                "name": "Saturation Index",
                "value": -0.13,
                "unit": "lsi",
                "state_type": "measurement",
            },
            "ph_probe_water_temp": {
                "name": "pH Probe Water Temperature",
                "value": 56,
                "unit": "°F",
                "device_type": "temperature",
                "state_type": "measurement",
            },
        },
        "configuration": {
            "ph_setpoint": {"name": "pH Setpoint", "value": 7.5, "unit": "pH"},
            "orp_setpoint": {"name": "ORP Setpoint", "value": 700, "unit": "mV"},
            "calcium_harness": {
                "name": "Calcium Hardness",
                "value": 740,
                "unit": "ppm",
            },
            "cya": {"name": "Cyanuric Acid", "value": 36, "unit": "ppm"},
            "total_alkalinity": {
                "name": "Total Alkalinity",
                "value": 70,
                "unit": "ppm",
            },
            "salt_tds_ppm": {"name": "Salt/TDS", "value": 1000, "unit": "ppm"},
            "probe_is_celsius": 0,
            "flags": 32,
        },
        "dose_status": {
            "ph_last_dose_time": {
                "name": "Last pH Dose Time",
                "value": 5,
                "unit": "sec",
                "device_type": "duration",
                "state_type": "total_increasing",
            },
            "orp_last_dose_time": {
                "name": "Last ORP Dose Time",
                "value": 2,
                "unit": "sec",
                "device_type": "duration",
                "state_type": "total_increasing",
            },
            "ph_last_dose_volume": {
                "name": "Last pH Dose Volume",
                "value": 10,
                "unit": "mL",
                "device_type": "volume",
                "state_type": "total_increasing",
            },
            "orp_last_dose_volume": {
                "name": "Last ORP Dose Volume",
                "value": 4,
                "unit": "mL",
                "device_type": "volume",
                "state_type": "total_increasing",
            },
            "flags": 165,
            "ph_dosing_state": {
                "name": "pH Dosing State",
                "value": 2,
                "device_type": "enum",
                "enum_options": ["Dosing", "Mixing", "Monitoring"],
            },
            "orp_dosing_state": {
                "name": "ORP Dosing State",
                "value": 2,
                "device_type": "enum",
                "enum_options": ["Dosing", "Mixing", "Monitoring"],
            },
        },
        "alarm": {
            "flags": 129,
            "flow_alarm": {"name": "Flow Alarm", "value": 1, "device_type": "alarm"},
            "ph_high_alarm": {
                "name": "pH HIGH Alarm",
                "value": 0,
                "device_type": "alarm",
            },
            "ph_low_alarm": {
                "name": "pH LOW Alarm",
                "value": 0,
                "device_type": "alarm",
            },
            "orp_high_alarm": {
                "name": "ORP HIGH Alarm",
                "value": 0,
                "device_type": "alarm",
            },
            "orp_low_alarm": {
                "name": "ORP LOW Alarm",
                "value": 0,
                "device_type": "alarm",
            },
            "ph_supply_alarm": {
                "name": "pH Supply Alarm",
                "value": 0,
                "device_type": "alarm",
            },
            "orp_supply_alarm": {
                "name": "ORP Supply Alarm",
                "value": 0,
                "device_type": "alarm",
            },
            "probe_fault_alarm": {
                "name": "Probe Fault",
                "value": 1,
                "device_type": "alarm",
            },
        },
        "alert": {
            "flags": 0,
            "ph_lockout": {"name": "pH Lockout", "value": 0},
            "ph_limit": {"name": "pH Dose Limit Reached", "value": 0},
            "orp_limit": {"name": "ORP Dose Limit Reached", "value": 0},
        },
        "firmware": {"name": "IntelliChem Firmware", "value": "1.060"},
        "water_balance": {
            "flags": 0,
            "corrosive": {"name": "SI Corrosive", "value": 0, "device_type": "alarm"},
            "scaling": {"name": "SI Scaling", "value": 0, "device_type": "alarm"},
        },
        "unknown_at_offset_44": 0,
        "unknown_at_offset_45": 0,
        "unknown_at_offset_46": 0,
    },
    "scg": {
        "scg_present": 0,
        "sensor": {
            "state": {"name": "SCG State", "value": 1},
            "salt_ppm": {
                "name": "SCG Salt",
                "value": 0,
                "unit": "ppm",
                "state_type": "measurement",
            },
        },
        "configuration": {
            "pool_setpoint": {"name": "Pool SCG Setpoint", "value": 50, "unit": "%"},
            "spa_setpoint": {"name": "Spa SCG Setpoint", "value": 0, "unit": "%"},
            "super_chlor_timer": {
                "name": "SCG Super Chlorination Timer",
                "value": 0,
                "unit": "hr",
            },
        },
        "flags": 0,
    },
}
